ut-error deprecations
softwaregroup-bg/ut-codec-ndc pull request #17
Opened 2018-09-19 12:25 UTC by Kristiyan-Todorov

2018-09-26 10:40 UTC, Kristiyan-Todorov commented
depends on changes in [ut-port-tcp](https://github.com/softwaregroup-bg/ut-port-tcp/pull/14)

2018-09-26 10:42 UTC, zetxx approved these changes

2018-09-28 05:53 UTC, kalinkrustev requested changes

2018-09-28 05:53 UTC, kalinkrustev commented on errors.js
> +    const customReject = status => {
This needs discussion

2018-10-01 07:17 UTC, kalinkrustev approved these changes

2018-10-01 07:17 UTC, merged